// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx5ttZmKFb6XgtBzEZdgDD9gTI630dzhI',
    appId: '1:1036328355684:web:52b1b21916f4ce50b39c71',
    messagingSenderId: '1036328355684',
    projectId: 'firstprojectv2-2025',
    authDomain: 'firstprojectv2-2025.firebaseapp.com',
    storageBucket: 'firstprojectv2-2025.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsc4nFunThysnmsCPjiHIm4h_7ySJV2k',
    appId: '1:1036328355684:ios:bd7411b85d40230bb39c71',
    messagingSenderId: '1036328355684',
    projectId: 'firstprojectv2-2025',
    storageBucket: 'firstprojectv2-2025.firebasestorage.app',
    iosBundleId: 'com.himanshu.firstprojectv2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsc4nFunThysnmsCPjiHIm4h_7ySJV2k',
    appId: '1:1036328355684:ios:bd7411b85d40230bb39c71',
    messagingSenderId: '1036328355684',
    projectId: 'firstprojectv2-2025',
    storageBucket: 'firstprojectv2-2025.firebasestorage.app',
    iosBundleId: 'com.himanshu.firstprojectv2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMurUA_HGWyrO4z3q_4QRloXB4agGkKZ0',
    appId: '1:1036328355684:android:dec478a9b421a12bb39c71',
    messagingSenderId: '1036328355684',
    projectId: 'firstprojectv2-2025',
    storageBucket: 'firstprojectv2-2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPZ4kpqfvEDxcvNC-_86mpfLLqJq3Lwr8',
    appId: '1:1036328355684:web:caa2b3d530a83976b39c71',
    messagingSenderId: '1036328355684',
    projectId: 'firstprojectv2-2025',
    authDomain: 'firstprojectv2-2025.firebaseapp.com',
    storageBucket: 'firstprojectv2-2025.firebasestorage.app',
  );

}