// File generated by FlutterFire CLI (customized to your current setup).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;

      // Not configured yet — add these platforms with FlutterFire when needed:
      case TargetPlatform.android:
        throw _notConfigured('android', 'flutterfire configure --platforms=android');
      case TargetPlatform.iOS:
        throw _notConfigured('ios', 'flutterfire configure --platforms=ios');
      case TargetPlatform.windows:
        throw _notConfigured('windows', 'flutterfire configure --platforms=windows');
      case TargetPlatform.linux:
        throw _notConfigured('linux', 'flutterfire configure --platforms=linux');

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static UnsupportedError _notConfigured(String platform, String hint) =>
      UnsupportedError(
        'DefaultFirebaseOptions have not been configured for $platform. '
        'Run: $hint (and re-run for any other platforms you need).',
      );

  // -------- Web (configured) --------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxIufeuG9Xq5KhOYvbsFWyRqceFPnqGc',
    appId: '1:102032978405:web:c5f409435b872328bf7f0c',
    messagingSenderId: '102032978405',
    projectId: 'peak-sunset-461808-n2',
    authDomain: 'peak-sunset-461808-n2.firebaseapp.com',
    storageBucket: 'peak-sunset-461808-n2.firebasestorage.app',
    measurementId: 'G-2HD306K0WW',
  );

  // -------- macOS (configured) --------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_wXt0NZ8C1DaPHHDdsDmc8WjKaCph7s',
    appId: '1:102032978405:ios:be936e2b6fcefc53bf7f0c',
    messagingSenderId: '102032978405',
    projectId: 'peak-sunset-461808-n2',
    storageBucket: 'peak-sunset-461808-n2.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  // When you add more platforms later, FlutterFire will append blocks like:
  //
  // static const FirebaseOptions android = FirebaseOptions(...);
  // static const FirebaseOptions ios = FirebaseOptions(...);
  // static const FirebaseOptions windows = FirebaseOptions(...);
  // static const FirebaseOptions linux = FirebaseOptions(...);
}
