import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire (may miss macOS)
import 'package:provider/provider.dart';
import 'auth_service.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'package:first_project/calorie_tracker_provider.dart';
import 'package:first_project/login_page.dart';
import 'package:first_project/home_page.dart';

Future<void> _initFirebase() async {
  // Avoid re-initializing during hot reload
  if (Firebase.apps.isNotEmpty) return;

  // Web must always pass options
  if (kIsWeb) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.web);
    return;
  }

  // Apple/Android desktop & mobile
  if (Platform.isMacOS) {
    // Try using firebase_options.dart first; if macOS block is missing,
    // fall back to reading macos/Runner/GoogleService-Info.plist.
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (_) {
      await Firebase.initializeApp(); // uses the macOS plist you downloaded
    }
    return;
  }

  // iOS/Android/Windows/Linux – use the generated options normally
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _initFirebase();

  runApp(
    ChangeNotifierProvider(
      create: (_) => CalorieTrackerProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CalTrack',
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF4CAF50),
      ),
      home: StreamBuilder<User?>(
        stream: AuthService().authStateChanges,
        builder: (context, snap) {
          if (snap.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          if (snap.data == null) {
            return const LoginPage();
          }
          return const HomePage();
        },
      ),
    );
  }
}
